# Name(s)
Xavier Graham

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

I don't have many questions, but I always have trouble with the setup of these workspaces, and was wondering if it was better to setup a remote way to access my jupyter notebook from my computer, or to rather just use the hub online and then download it in order to git commit it as my solution?

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [18]:
import numpy as np

a = np.full((6, 4), 2)
print(a)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


## Exercise 2

In [41]:
import numpy as np

b = np.full((6, 4), 1)
np.fill_diagonal(b, 3)
print(b)

[[3 1 1 1]
 [1 3 1 1]
 [1 1 3 1]
 [1 1 1 3]
 [1 1 1 1]
 [1 1 1 1]]


## Exercise 3

In [20]:
import numpy as np

# You cannot multiply the two matrices together because they are both 6 x 4
# In order to multiply matrices, the number of columns in the first matrix must
# equal the number of rows in the second matrix

# a * b does not multiply the matrices, simply the individual components in a
# 1-to-1 fashion

print(a * b)

# dot(a, b) attempts to multiply the matrices, which is why it doesnt work

# print(np.dot(a, b))

[[6 2 2 2]
 [2 6 2 2]
 [2 2 6 2]
 [2 2 2 6]
 [2 2 2 2]
 [2 2 2 2]]


## Exercise 4

In [21]:
import numpy as np

print(np.dot(a.transpose(), b))
print(np.dot(a, b.transpose()))

# The above outputs are different shapes because in the first one, we are
# matrix multiplying a 4 x 6 matrix by a 6 x 4 matrix, resulting in a 4 x 4 matrix

# The second one is multiplying a 6 x 4 matrix by a 4 x 6 matrix, resulting in
# a 6 x 6 matrix

[[16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]]
[[12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]]


## Exercise 5

In [22]:
import numpy as np

def definitely_not_lyrics():
    print("Is this the real life? Is this just fantasy?")
    print("Caught in a landslide, no escape from reality")
    print("Open your eyes, look up to the skies and see")
    print("I'm just a poor boy, I need no sympathy")
    print("Because I'm easy come, easy go, little high, little low")
    print("Any way the wind blows doesn't really matter to me, to me")

definitely_not_lyrics()

Is this the real life? Is this just fantasy?
Caught in a landslide, no escape from reality
Open your eyes, look up to the skies and see
I'm just a poor boy, I need no sympathy
Because I'm easy come, easy go, little high, little low
Any way the wind blows doesn't really matter to me, to me


## Exercise 6

In [23]:
import numpy as np
import random
import array as arr

def print_array(arr_in):
    print("[", end = "")
    for i in range(len(arr_in) - 1):
        print(arr_in[i], end = ", ")
    print(arr_in[i + 1], "]", sep = "")

def create_rand_array():
    random_stuff = arr.array('i', [])
    # Generate array
    for i in range(10):
        random_stuff.append(random.randint(0, 100))
    # Print array
    print("ARRAY: ", end = "")
    print_array(random_stuff)
    # Print sum
    print("SUM:", np.sum(random_stuff, dtype = np.uint8))
    # Print mean value
    print("MEAN:", np.mean(random_stuff))
        
create_rand_array()
print()
create_rand_array()
print()
create_rand_array()
print()

ARRAY: [30, 86, 15, 32, 4, 40, 31, 33, 11, 73]
SUM: 99
MEAN: 35.5

ARRAY: [93, 91, 72, 72, 4, 63, 8, 81, 84, 2]
SUM: 58
MEAN: 57.0

ARRAY: [50, 69, 96, 91, 10, 73, 31, 70, 35, 38]
SUM: 51
MEAN: 56.3



## Exercise 7

In [24]:
import numpy as np
import array

def count_ones_nowhere(arr_in):
    sum = 0
    for row in arr_in:
        for num in row:
            if num == 1:
                sum += 1;
    return sum

def count_ones_where(arr_in):
    return np.sum(np.where(arr_in == 1, 1, 0))


c = np.array([[3, 2, 1, -9, 1, 0],
              [1, -2, 1, 8, -2, 10],
              [5, 2, 3, 4, 5, 15],
              [1, -1, 0, -9, 1, 1],
              [0, 1, 7, 7, 1, 1],
              [3, 1, -1, 8, 0, 12]])

print(count_ones_where(c))
print(count_ones_nowhere(c))

11
11


## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [32]:
import pandas as pd

col_names = ['1', '2', '3', '4']
row_names = ['1', '2', '3', '4', '5', '6']
a = pd.DataFrame(dtype = int, columns = col_names, index = row_names)

for i in row_names:
    a.loc[i] = pd.Series({'1': 2, '2': 2, '3': 2, '4': 2})

print(a)

     1    2    3    4
1  2.0  2.0  2.0  2.0
2  2.0  2.0  2.0  2.0
3  2.0  2.0  2.0  2.0
4  2.0  2.0  2.0  2.0
5  2.0  2.0  2.0  2.0
6  2.0  2.0  2.0  2.0


## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [49]:
import pandas as pd

b = pd.DataFrame(np.ones((6, 4)))
b.iloc[range(4), range(4)] = 3
    
b

0    1    2    3
0  3.0  1.0  1.0  1.0
1  1.0  3.0  1.0  1.0
2  1.0  1.0  3.0  1.0
3  1.0  1.0  1.0  3.0
4  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [28]:
import pandas as pd

# Same as above, you cannot multiply the two matrices together because they are both 6 x 4
# so the row and column counts do not match up

# a * b multiplies the individual components in a 1-to-1 fashion

print(a * b)

# dot(a, b) attempts to multiply the matrices, which is why it doesnt work
# print(np.dot(a, b))

     1    2    3    4
1  6.0  2.0  2.0  2.0
2  2.0  6.0  2.0  2.0
3  2.0  2.0  6.0  2.0
4  2.0  2.0  2.0  6.0
5  2.0  2.0  2.0  2.0
6  2.0  2.0  2.0  2.0


## Exercise 11
Repeat exercise A.7 using a dataframe.

In [29]:
import pandas as pd

def count_ones_nowhere(frame_in):
    sum = 0.0
    for label, content in frame_in.items():
        for index, value in content.items():
            if value == 1:
                sum += 1;
    return sum

def count_ones_where(frame_in):
    return frame_in.where(frame_in == 1.0, other = 0).sum(numeric_only = True).sum()
    
print(count_ones_nowhere(b))
print(count_ones_where(b))


20.0
20.0


## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [85]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)

titanic_df

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [86]:
import pandas as pd

out_df = titanic_df.get("name")
print(out_df)

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...                       
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object


## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [87]:
titanic_df.set_index('sex',inplace = True)
# Get female passengers only using the line below
female_df = titanic_df.loc["female"]
print(female_df)
# Number of female passengers
print("NUMBER OF FEMALES:", len(female_df.index))

        pclass  survived                                             name  \
sex                                                                         
female       1         1                    Allen, Miss. Elisabeth Walton   
female       1         0                     Allison, Miss. Helen Loraine   
female       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
female       1         1                Andrews, Miss. Kornelia Theodosia   
female       1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)   
...        ...       ...                                              ...   
female       3         1  Whabee, Mrs. George Joseph (Shawneene Abi-Saab)   
female       3         1                 Wilkes, Mrs. James (Ellen Needs)   
female       3         1          Yasbeck, Mrs. Antoni (Selini Alexander)   
female       3         0                             Zabour, Miss. Hileni   
female       3         0                            Zabour, Miss. Thamine   

## Exercise 14
How do you reset the index?

In [88]:
# Reset index
titanic_df.reset_index()

sex  pclass  survived  \
0     female       1         1   
1       male       1         1   
2     female       1         0   
3       male       1         0   
4     female       1         0   
...      ...     ...       ...   
1304  female       3         0   
1305  female       3         0   
1306    male       3         0   
1307    male       3         0   
1308    male       3         0   

                                                 name      age  sibsp  parch  \
0                       Allen, Miss. Elisabeth Walton  29.0000      0      0   
1                      Allison, Master. Hudson Trevor   0.9167      1      2   
2                        Allison, Miss. Helen Loraine   2.0000      1      2   
3                Allison, Mr. Hudson Joshua Creighton  30.0000      1      2   
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0000      1      2   
...                                               ...      ...    ...    ...   
1304                             Zabour, Miss. Hileni  14.5000      1      0   
1305                            Zabour, Miss. Thamine      NaN      1      0   
1306                        Zakarian, Mr. Mapriededer  26.5000      0      0   
1307                              Zakarian, Mr. Ortin  27.0000      0      0   
1308                               Zimmerman, Mr. Leo  29.0000      0      0   

      ticket      fare    cabin embarked boat   body  \
0      24160  211.3375       B5        S    2    NaN   
1     113781  151.5500  C22 C26        S   11    NaN   
2     113781  151.5500  C22 C26        S  NaN    NaN   
3     113781  151.5500  C22 C26        S  NaN  135.0   
4     113781  151.5500  C22 C26        S  NaN    NaN   
...      ...       ...      ...      ...  ...    ...   
1304    2665   14.4542      NaN        C  NaN  328.0   
1305    2665   14.4542      NaN        C  NaN    NaN   
1306    2656    7.2250      NaN        C  NaN  304.0   
1307    2670    7.2250      NaN        C  NaN    NaN   
1308  315082    7.8750      NaN        S  NaN    NaN   

                            home.dest  
0                        St Louis, MO  
1     Montreal, PQ / Chesterville, ON  
2     Montreal, PQ / Chesterville, ON  
3     Montreal, PQ / Chesterville, ON  
4     Montreal, PQ / Chesterville, ON  
...                               ...  
1304                              NaN  
1305                              NaN  
1306                              NaN  
1307                              NaN  
1308                              NaN  

[1309 rows x 14 columns]